<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="log_request_error_messages" skipped="0" tests="1" time="26.81" timestamp="2022-06-20T16:35:32">
	<testcase classname="LogRequestVerifySearchTextError" name="log_request_error_messages">
		<failure message="BLOCKED: TypeError: 'NoneType' object is not subscriptable" type="BLOCKED"/>
		<system-out>16:35:05 INFO  ==============================================================
16:35:05 INFO  Id:    log_request_error_messages
16:35:05 INFO  Dir:   log_request_end_to_end/
16:35:05 INFO  Title: Validate end to end behaviour for the log request operation check for error messages
16:35:05 INFO  ==============================================================
16:35:07 INFO  EnvironmentC8y Setup
16:35:07 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
16:35:21 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 13 secs
16:35:22 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
16:35:22 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
16:35:23 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
16:35:23 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
16:35:24 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
16:35:24 INFO  Executed sudo&lt;log_file_daemon&gt;, exit status 0
16:35:25 WARN  TypeError occurred while running test - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1294, in __call__
    self.testObj.execute()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_error_messages/run.py&quot;, line 47, in execute
    log_file_request_payload, self.project.deviceid
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/environments/cumulocity.py&quot;, line 101, in trigger_log_request
    &quot;deviceId&quot;: self.device_fragment[&quot;id&quot;],
TypeError: 'NoneType' object is not subscriptable
16:35:25 WARN  TypeError: 'NoneType' object is not subscriptable ... blocked 
16:35:25 INFO  
16:35:25 INFO  cleanup:
16:35:26 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
16:35:26 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
16:35:27 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
16:35:28 INFO  Executed sudo&lt;log_file_daemon&gt;, exit status 0
16:35:32 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
16:35:32 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
16:35:32 INFO  
16:35:32 INFO  Test duration: 26.81 secs
16:35:32 INFO  Test final outcome:  BLOCKED
16:35:32 INFO  Test outcome reason: TypeError: 'NoneType' object is not subscriptable
16:35:32 INFO  
</system-out>
	</testcase>
</testsuite>
