<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_finalize" skipped="0" tests="1" time="7.06" timestamp="2022-05-23T12:03:56">
	<testcase classname="DockerPluginFinalizeTest" name="docker_plugin_finalize">
		<failure message="BLOCKED: sudo&lt;docker_pull&gt; returned non-zero exit code 1" type="BLOCKED"/>
		<system-out>12:03:49 INFO  ==============================================================
12:03:49 INFO  Id:    docker_plugin_finalize
12:03:49 INFO  Dir:   plugin_docker/
12:03:49 INFO  Title: Validate docker plugin finalize command
12:03:49 INFO  ==============================================================
12:03:53 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
12:03:53 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_finalize/Output/linux/docker_images.out ... passed
12:03:56 WARN  Executed sudo&lt;docker_pull&gt;, exit status 1
12:03:56 INFO  Contents of docker_pull.err: 
  Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
  -----

12:03:56 WARN  sudo&lt;docker_pull&gt; returned non-zero exit code 1 ... blocked 
12:03:56 WARN  Aborted test due to BLOCKED outcome
12:03:56 INFO  
12:03:56 INFO  cleanup:
12:03:56 INFO  
12:03:56 INFO  Test duration: 7.06 secs
12:03:56 INFO  Test final outcome:  BLOCKED
12:03:56 INFO  Test outcome reason: sudo&lt;docker_pull&gt; returned non-zero exit code 1
12:03:56 INFO  
</system-out>
	</testcase>
</testsuite>
