<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="docker_plugin_update" skipped="0" tests="1" time="39.6" timestamp="2022-06-22T19:38:38">
	<testcase classname="DockerPluginUpdateTest" name="docker_plugin_update">
		<failure message="BLOCKED: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+1 other failures)" type="BLOCKED"/>
		<system-out>19:37:59 INFO  ==============================================================
19:37:59 INFO  Id:    docker_plugin_update
19:37:59 INFO  Dir:   plugin_docker/
19:37:59 INFO  Title: Validate docker plugin install updates existing containers
19:37:59 INFO  ==============================================================
19:38:00 INFO  Executed sudo&lt;docker_images&gt;, exit status 0
19:38:00 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_images.out ... passed
19:38:25 INFO  Executed sudo&lt;docker_run&gt;, exit status 0, duration 25 secs
19:38:26 INFO  Executed sudo&lt;docker_ps&gt;, exit status 0
19:38:26 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_ps.out ... passed
19:38:31 WARN  Executed sudo&lt;plugin_install&gt;, exit status 2
19:38:31 WARN  sudo&lt;plugin_install&gt; returned non-zero exit code 2 ... blocked [environment_docker_plugin.py:136,environment_docker_plugin.py:144,run.py:30]
19:38:32 INFO  Executed sudo&lt;docker_ps_latest&gt;, exit status 0
19:38:33 INFO  Executed sudo&lt;docker_ps&gt;, exit status 0
19:38:33 INFO  Grep on file /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_ps.out ... passed
19:38:34 INFO  Executed sudo&lt;docker_ps&gt;, exit status 0
19:38:34 WARN  Grep on /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/plugin_docker/docker_plugin_update/Output/linux/docker_ps.out contains &quot;registry:2.7.1&quot; ... failed [environment_docker_plugin.py:49,run.py:39]
19:38:34 INFO  
19:38:34 INFO  cleanup:
19:38:34 INFO  Removing containers scheduled to be cleaned up: ['9ad923d446e9', '', 'd35cc9a56380a0b2ef89c9e3282820639e0b6db2b1552de0f7291b4b94ba247f\n', '']
19:38:35 WARN  Executed sudo&lt;containers_for_cleanup&gt;, exit status 1
19:38:35 INFO  Removing images scheduled to be cleaned up: ['registry', 'registry:2.7.1', 'registry:2.6.2', 'registry:2.7.1']
19:38:38 INFO  Executed sudo&lt;containers_for_cleanup&gt;, exit status 0
19:38:38 INFO  
19:38:38 INFO  Test duration: 39.60 secs
19:38:38 INFO  Test final outcome:  BLOCKED
19:38:38 INFO  Test outcome reason: sudo&lt;plugin_install&gt; returned non-zero exit code 2 (+1 other failures)
19:38:38 INFO  
</system-out>
	</testcase>
</testsuite>
