<?xml version="1.0" encoding="utf-8"?>
<testsuite failures="1" name="log_request_num_lines" skipped="0" tests="1" time="54.66" timestamp="2022-05-23T13:18:11">
	<testcase classname="LogRequestVerifyNumberOfLines" name="log_request_num_lines">
		<failure message="BLOCKED: Exception: retry" type="BLOCKED"/>
		<system-out>13:17:16 INFO  ==============================================================
13:17:16 INFO  Id:    log_request_num_lines
13:17:16 INFO  Dir:   log_request_end_to_end/
13:17:16 INFO  Title: Validate end to end behaviour for the log request operation check for number of lines
13:17:16 INFO  ==============================================================
13:17:16 INFO  EnvironmentC8y Setup
13:17:16 INFO  Executed systemctl&lt;serv_mapper1&gt;, exit status 3
13:17:17 INFO  Restarting mosquitto too frequently in the last 10 seconds. It was only up for 4 seconds
13:17:17 INFO  Delaying execution by 7 seconds
13:17:38 INFO  Executed sudo&lt;tedge_connect_c8y&gt;, exit status 0, duration 14 secs
13:17:38 INFO  Executed sudo&lt;tedge_connect_c8y_test&gt;, exit status 0
13:17:39 INFO  Executed systemctl&lt;serv_mosq2&gt;, exit status 0
13:17:39 INFO  Executed systemctl&lt;serv_mapper3&gt;, exit status 0
13:17:40 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
13:17:41 INFO  Executed sudo&lt;move_logs&gt;, exit status 0
13:17:41 INFO  log response None
13:17:41 WARN  retry, retrying in 1 seconds...
13:17:42 INFO  log response None
13:17:42 WARN  retry, retrying in 1 seconds...
13:17:43 INFO  log response None
13:17:43 WARN  retry, retrying in 1 seconds...
13:17:45 INFO  log response None
13:17:45 WARN  retry, retrying in 1 seconds...
13:17:46 INFO  log response None
13:17:46 WARN  retry, retrying in 1 seconds...
13:17:47 INFO  log response None
13:17:47 WARN  retry, retrying in 1 seconds...
13:17:48 INFO  log response None
13:17:48 WARN  retry, retrying in 1 seconds...
13:17:50 INFO  log response None
13:17:50 WARN  retry, retrying in 1 seconds...
13:17:51 INFO  log response None
13:17:51 WARN  retry, retrying in 1 seconds...
13:17:52 INFO  log response None
13:17:52 WARN  retry, retrying in 1 seconds...
13:17:53 INFO  log response None
13:17:53 WARN  retry, retrying in 1 seconds...
13:17:54 INFO  log response None
13:17:54 WARN  retry, retrying in 1 seconds...
13:17:56 INFO  log response None
13:17:56 WARN  retry, retrying in 1 seconds...
13:17:57 INFO  log response None
13:17:57 WARN  retry, retrying in 1 seconds...
13:17:58 INFO  log response None
13:17:58 WARN  retry, retrying in 1 seconds...
13:17:59 INFO  log response None
13:17:59 WARN  retry, retrying in 1 seconds...
13:18:01 INFO  log response None
13:18:01 WARN  retry, retrying in 1 seconds...
13:18:02 INFO  log response None
13:18:02 WARN  retry, retrying in 1 seconds...
13:18:03 INFO  log response None
13:18:03 WARN  retry, retrying in 1 seconds...
13:18:04 INFO  log response None
13:18:04 WARN  Exception occurred while running test - retry
Traceback (most recent call last):
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/pysys/baserunner.py&quot;, line 1296, in __call__
    self.testObj.validate()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/run.py&quot;, line 44, in validate
    self.assertThat(&quot;True == value&quot;, value=self.wait_until_logs_retrieved())
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/decorator.py&quot;, line 232, in fun
    return caller(func, *(extras + args), **kw)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py&quot;, line 74, in retry_decorator
    logger)
  File &quot;/home/pi/env-pysys/lib/python3.7/site-packages/retry/api.py&quot;, line 33, in __retry_internal
    return f()
  File &quot;/home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/tests/PySys/log_request_end_to_end/log_request_num_lines/run.py&quot;, line 52, in wait_until_logs_retrieved
    raise Exception(&quot;retry&quot;)
Exception: retry
13:18:04 WARN  Exception: retry ... blocked 
13:18:04 INFO  
13:18:04 INFO  cleanup:
13:18:05 INFO  Executed sudo&lt;rm_logs&gt;, exit status 0
13:18:05 INFO  Executed sudo&lt;rm_tmp_logs&gt;, exit status 0
13:18:06 INFO  Executed sudo&lt;send_failed&gt;, exit status 0
13:18:10 INFO  Executed sudo&lt;tedge_disconnect_c8y&gt;, exit status 0
13:18:11 INFO  Executed systemctl&lt;serv_mapper5&gt;, exit status 3
13:18:11 INFO  
13:18:11 INFO  Test duration: 54.66 secs
13:18:11 INFO  Test final outcome:  BLOCKED
13:18:11 INFO  Test outcome reason: Exception: retry
13:18:11 INFO  
</system-out>
	</testcase>
</testsuite>
